package com.deruy.plugin.lifesteal;
import com.deruy.plugin.DeruyPlugin;import com.deruy.plugin.lifesteal.listeners.HeartRestoreListener;import org.bukkit.*;import org.bukkit.enchantments.Enchantment;import org.bukkit.entity.Player;import org.bukkit.event.*;import org.bukkit.event.block.Action;import org.bukkit.event.inventory.InventoryClickEvent;import org.bukkit.event.player.PlayerInteractEvent;import org.bukkit.inventory.*;import org.bukkit.inventory.meta.*;import org.bukkit.persistence.PersistentDataType;import java.util.*;
/** 부활 아이템 → 사망자 머리 목록 → 확인 GUI. */
public final class ReviveItemManager implements Listener{
 public static final NamespacedKey KEY=new NamespacedKey("deruy","revive_item"),TARGET=new NamespacedKey("deruy","revive_target");private final DeruyPlugin plugin;public ReviveItemManager(DeruyPlugin p){plugin=p;}
 public ItemStack create(){Material mat=material("revive-item.material",Material.TOTEM_OF_UNDYING);ItemStack i=new ItemStack(mat);ItemMeta m=i.getItemMeta();m.setDisplayName(ChatColor.translateAlternateColorCodes('&',plugin.getConfig().getString("revive-item.name","&d&l부활의 심장")));m.setLore(List.of("§7우클릭하여 부활시킬 플레이어를 선택합니다."));m.getPersistentDataContainer().set(KEY,PersistentDataType.BYTE,(byte)1);int model=plugin.getConfig().getInt("revive-item.custom-model-data",0);if(model>0)m.setCustomModelData(model);m.addEnchant(Enchantment.UNBREAKING,1,true);m.addItemFlags(ItemFlag.HIDE_ENCHANTS);i.setItemMeta(m);return i;}
 private Material material(String path,Material d){try{return Material.valueOf(plugin.getConfig().getString(path,d.name()).toUpperCase());}catch(Exception e){return d;}}
 public boolean is(ItemStack i){return i!=null&&i.hasItemMeta()&&i.getItemMeta().getPersistentDataContainer().has(KEY,PersistentDataType.BYTE);}
 @EventHandler public void interact(PlayerInteractEvent e){if((e.getAction()!=Action.RIGHT_CLICK_AIR&&e.getAction()!=Action.RIGHT_CLICK_BLOCK)||!is(e.getItem()))return;e.setCancelled(true);openList(e.getPlayer());}
 private void openList(Player p){List<org.bukkit.OfflinePlayer> dead=Arrays.stream(Bukkit.getOfflinePlayers()).filter(x->plugin.getDataStore().isHeartBan(x.getUniqueId())).toList();int size=Math.max(9,Math.min(54,((dead.size()+8)/9)*9));Inventory inv=Bukkit.createInventory(null,size,"§4부활할 플레이어 선택");for(int n=0;n<Math.min(size,dead.size());n++){var target=dead.get(n);ItemStack head=new ItemStack(Material.PLAYER_HEAD);SkullMeta m=(SkullMeta)head.getItemMeta();m.setOwningPlayer(target);m.setDisplayName("§e"+Objects.toString(target.getName(),target.getUniqueId().toString()));m.getPersistentDataContainer().set(TARGET,PersistentDataType.STRING,target.getUniqueId().toString());head.setItemMeta(m);inv.setItem(n,head);}p.openInventory(inv);}
 @EventHandler public void click(InventoryClickEvent e){String title=e.getView().getTitle();if(!title.equals("§4부활할 플레이어 선택")&&!title.equals("§4부활 확인"))return;e.setCancelled(true);if(!(e.getWhoClicked() instanceof Player p)||e.getCurrentItem()==null)return;if(title.equals("§4부활할 플레이어 선택")){String id=e.getCurrentItem().getItemMeta().getPersistentDataContainer().get(TARGET,PersistentDataType.STRING);if(id!=null)openConfirm(p,UUID.fromString(id));return;}if(e.getSlot()==15){p.closeInventory();return;}if(e.getSlot()!=11)return;String id=e.getInventory().getItem(13).getItemMeta().getPersistentDataContainer().get(TARGET,PersistentDataType.STRING);revive(p,UUID.fromString(id));}
 private void openConfirm(Player p,UUID id){OfflinePlayer target=Bukkit.getOfflinePlayer(id);Inventory inv=Bukkit.createInventory(null,27,"§4부활 확인");ItemStack head=new ItemStack(Material.PLAYER_HEAD);SkullMeta hm=(SkullMeta)head.getItemMeta();hm.setOwningPlayer(target);hm.setDisplayName("§e"+Objects.toString(target.getName(),id.toString()));hm.getPersistentDataContainer().set(TARGET,PersistentDataType.STRING,id.toString());head.setItemMeta(hm);inv.setItem(13,head);ItemStack yes=new ItemStack(Material.LIME_CONCRETE);ItemMeta ym=yes.getItemMeta();ym.setDisplayName("§a부활시키기");yes.setItemMeta(ym);inv.setItem(11,yes);ItemStack no=new ItemStack(Material.RED_CONCRETE);ItemMeta nm=no.getItemMeta();nm.setDisplayName("§c취소");no.setItemMeta(nm);inv.setItem(15,no);p.openInventory(inv);}
 private void revive(Player user,UUID id){if(!plugin.getDataStore().isHeartBan(id)){user.sendMessage("§c이미 부활했거나 부활 대상이 아닙니다.");user.closeInventory();return;}int slot=-1;for(int n=0;n<user.getInventory().getSize();n++)if(is(user.getInventory().getItem(n))){slot=n;break;}if(slot<0){user.sendMessage("§c부활 아이템이 없습니다.");return;}OfflinePlayer target=Bukkit.getOfflinePlayer(id);org.bukkit.BanList<org.bukkit.profile.PlayerProfile> bans=Bukkit.getBanList(org.bukkit.BanList.Type.PROFILE);var entry=bans.getBanEntry(target.getPlayerProfile());if(entry!=null&&!"LifeSteal".equals(entry.getSource())){user.sendMessage("§c다른 사유로 밴된 플레이어입니다.");return;}int hearts=plugin.getConfig().getInt("heart.revive-hearts",10);plugin.getDataStore().queueHeartRestore(id,hearts);plugin.getDataStore().setHeartBan(id,false);if(entry!=null)bans.pardon(target.getPlayerProfile());ItemStack item=user.getInventory().getItem(slot);item.setAmount(item.getAmount()-1);if(target.isOnline())HeartRestoreListener.apply(plugin,target.getPlayer());Bukkit.broadcastMessage("§d§l[부활] §f"+Objects.toString(target.getName(),id.toString())+"님이 부활했습니다!");user.closeInventory();}
}
