package com.deruy.plugin.randomevent;
import com.deruy.plugin.DeruyPlugin;
import org.bukkit.*;
import org.bukkit.entity.*;
import org.bukkit.inventory.*;
import org.bukkit.inventory.meta.PotionMeta;
import org.bukkit.potion.PotionType;
import org.bukkit.scheduler.BukkitTask;
import org.bukkit.util.*;
import org.joml.Vector3f;
import org.joml.Quaternionf;
import java.util.*;
import java.util.function.Consumer;
/** Private camera-relative item displays: no resource pack or inventory screen needed. */
public final class EventRoulette {
 private static final String TAG="deruy_event_roulette";
 private final DeruyPlugin plugin;private final List<RandomEventManager.Type> pool;private final RandomEventManager.Type winner;private final Consumer<RandomEventManager.Type> selected;private final Map<UUID,List<ItemDisplay>> displays=new HashMap<>();private BukkitTask task;private int tick;private final int duration;private final Map<UUID,Gui> screens=new HashMap<>();private final boolean camera;
 public static final class Gui implements InventoryHolder{final Inventory inventory;Gui(){inventory=Bukkit.createInventory(this,54,"§6랜덤 이벤트 추첨");}public Inventory getInventory(){return inventory;}}
 public EventRoulette(DeruyPlugin plugin,List<RandomEventManager.Type> pool,Consumer<RandomEventManager.Type> selected){this.plugin=plugin;camera=plugin.getConfig().getString("random-events.roulette-style","GUI").equalsIgnoreCase("CAMERA");this.pool=List.copyOf(pool);this.selected=selected;winner=pool.get(new Random().nextInt(pool.size()));duration=Math.clamp(plugin.getConfig().getInt("random-events.roulette-seconds",5),2,30)*20;}
 public void start(){Bukkit.getOnlinePlayers().forEach(p->p.sendTitle("§6랜덤 이벤트 추첨", "§f위에서 아래로 아이템이 돌아갑니다",5,duration+35,5));task=Bukkit.getScheduler().runTaskTimer(plugin,this::frame,1,2);}
 public static ItemStack icon(RandomEventManager.Type t){Material m=switch(t){case SHIELD_BAN,SWORD_SHIELD_BREAK->Material.SHIELD;case TOTEM_BAN->Material.TOTEM_OF_UNDYING;case POTION_BAN,POISON_HIT,STRENGTH_III,KILL_INVISIBILITY,PROJECTILE_WITHER->Material.POTION;case DOUBLE_DROPS->Material.DIAMOND;case MACE_BAN,MACE_DOUBLE_DAMAGE,MACE_SHOCKWAVE->Material.MACE;case KILL_DROP->Material.GOLDEN_APPLE;case CROP_REWARD->Material.WHEAT;case AXE_CRIT_SLOW->Material.DIAMOND_AXE;case TNT_DOUBLE_DAMAGE->Material.TNT;case PROJECTILE_BAN->Material.BOW;case KILL_VOUCHER->Material.CHEST;case COBWEB_BAN->Material.COBWEB;case LIFESTEAL->Material.REDSTONE;case COUNTERATTACK->Material.DIAMOND_SWORD;case POST_KILL_SPEED->Material.SUGAR;case FISHING_FRENZY->Material.FISHING_ROD;};ItemStack i=new ItemStack(m);if(i.getItemMeta() instanceof PotionMeta meta){meta.setBasePotionType(switch(t){case POISON_HIT->PotionType.POISON;case STRENGTH_III->PotionType.STRENGTH;case KILL_INVISIBILITY->PotionType.INVISIBILITY;case PROJECTILE_WITHER->PotionType.HARMING;default->PotionType.WATER;});if(t==RandomEventManager.Type.PROJECTILE_WITHER)meta.setColor(Color.BLACK);i.setItemMeta(meta);}return i;}
 private void frame(){try{tick+=2;Set<UUID> online=new HashSet<>();for(Player p:Bukkit.getOnlinePlayers()){online.add(p.getUniqueId());List<ItemDisplay> list=displays.get(p.getUniqueId());if(list!=null&&(list.stream().anyMatch(d->!d.isValid()||!d.getWorld().equals(p.getWorld())))){list.forEach(Entity::remove);displays.remove(p.getUniqueId());list=null;}if(camera&&list==null){list=new ArrayList<>();displays.put(p.getUniqueId(),list);for(int j=0;j<4;j++){ItemDisplay d=p.getWorld().spawn(p.getEyeLocation(),ItemDisplay.class,e->{e.setVisibleByDefault(false);e.setPersistent(false);e.setGravity(false);e.setInvulnerable(true);e.setBrightness(new Display.Brightness(15,15));e.setTeleportDuration(2);e.setDisplayWidth(6);e.setDisplayHeight(6);e.addScoreboardTag(TAG);});list.add(d);p.showEntity(plugin,d);}}
  if(!camera){Gui g=screens.get(p.getUniqueId());if(g==null){g=new Gui();screens.put(p.getUniqueId(),g);p.openInventory(g.inventory);}for(int row=0;row<6;row++){int slot=row*9+4;if(tick>=duration){g.inventory.setItem(slot,row==2?namedIcon(winner):null);}else g.inventory.setItem(slot,namedIcon(pool.get(Math.floorMod(row-tick/6,pool.size()))));}var marker=new ItemStack(tick>=duration?Material.LIME_STAINED_GLASS_PANE:Material.YELLOW_STAINED_GLASS_PANE);g.inventory.setItem(21,marker);g.inventory.setItem(23,marker);if(tick%6==0&&tick<duration)p.playSound(p.getLocation(),Sound.UI_BUTTON_CLICK,.35f,1.4f);if(tick==duration){p.sendTitle("§a선택된 이벤트",plugin.getConfig().getString("random-events.names."+winner.name(),winner.name()),5,35,5);p.playSound(p.getLocation(),Sound.ENTITY_PLAYER_LEVELUP,.8f,1.2f);}continue;}
  Location eye=p.getEyeLocation();org.bukkit.util.Vector forward=eye.getDirection().normalize();double yaw=Math.toRadians(eye.getYaw());org.bukkit.util.Vector right=new org.bukkit.util.Vector(Math.cos(yaw),0,Math.sin(yaw));org.bukkit.util.Vector up=forward.clone().crossProduct(right).normalize();boolean finished=tick>=duration;
  for(int j=0;j<list.size();j++){ItemDisplay d=list.get(j);if(finished&&j>0){d.setItemStack(new ItemStack(Material.AIR));continue;}double cycle=tick/8.0;double y=finished?0:1.25-((j+cycle)%4)*.8;RandomEventManager.Type type=finished?winner:pool.get(Math.floorMod(j+(int)Math.floor(cycle),pool.size()));d.setItemStack(icon(type));Location at=eye.clone().add(forward.clone().multiply(2.8)).add(up.clone().multiply(y));at.setYaw(eye.getYaw());at.setPitch(eye.getPitch());d.teleport(at);d.setTransformation(new Transformation(new Vector3f(),new Quaternionf().rotateY(tick*.14f),new Vector3f(finished?.75f:.48f),new Quaternionf()));}
  if(tick%8==0&&tick<duration)p.playSound(eye,Sound.UI_BUTTON_CLICK,.35f,1.4f);if(tick==duration){p.sendTitle("§a선택된 이벤트",plugin.getConfig().getString("random-events.names."+winner.name(),winner.name()),5,35,5);p.playSound(eye,Sound.ENTITY_PLAYER_LEVELUP,.8f,1.2f);}}
  for(UUID id:new ArrayList<>(displays.keySet()))if(!online.contains(id)){displays.remove(id).forEach(Entity::remove);}
  if(tick>=duration+30){cancel();selected.accept(winner);}
 }catch(RuntimeException e){plugin.getLogger().warning("추첨 표시 오류: "+e.getMessage());cancel();selected.accept(winner);}}
 private ItemStack namedIcon(RandomEventManager.Type t){var i=icon(t);i.editMeta(m->m.setDisplayName(ChatColor.translateAlternateColorCodes('&',plugin.getConfig().getString("random-events.names."+t.name(),t.name()))));return i;}
 public void cancel(){if(task!=null){task.cancel();task=null;}displays.values().forEach(list->list.forEach(Entity::remove));displays.clear();for(Player p:Bukkit.getOnlinePlayers()){var top=p.getOpenInventory().getTopInventory();Gui g=screens.get(p.getUniqueId());if(top!=null&&g!=null&&top==g.inventory)p.closeInventory();}screens.clear();}
}
